name: workshop
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  lighter_app:
    path: ./lighter_app
  basket_app:
    path: ./basket_app
  calculator_app:
    path: ./calculator_app
  xo_app:
    path: ./xo_app
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  math_expressions: ^2.6.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo/logo_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo/logo_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo/logo_icon.png"

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/icons/light.png
    - assets/images/icons/points.png
    - assets/images/icons/calculator.png
    - assets/images/icons/game_controller.png
    - assets/images/icons/Paw1.png
    - assets/images/icons/Paw2.png
    - assets/images/logo/

  fonts:
    - family: NerkoOne-Regular
      fonts:
        - asset: assets/fonts/NerkoOne-Regular.ttf